pipeline {
    agent any

    stages {
        stage('Restore') {
            steps {
                sh 'dotnet restore'
            }
        }

        stage('Build') {
            steps {
                sh 'dotnet build --configuration Release'
            }
        }

        stage('Run UI Tests') {
            steps {
                sh 'dotnet test --configuration Release --logger:"trx;LogFileName=test_results.trx"'
            }
        }
    }
}