pipeline {
    agent any

    tools {
        git 'Default'  // or the name from "Git installations"
    }


    stages {

        stage('Verify Git') {
             steps {
                sh 'git --version'
            }
        }

        stage('Restore') {
            steps {
                bat '"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe" "C:\\Users\\PrathameshBabanHarad\\source\\repos\\Training_UIAutomationFramework\\Training_UIAutomationFramework.sln" /t:Restore'
'
            }
        }

        stage('Build') {
            steps {
                bat '"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe" "C:\\Users\\PrathameshBabanHarad\\source\\repos\\Training_UIAutomationFramework\\Training_UIAutomationFramework.sln" /p:Configuration=Release /p:Platform="Any CPU"'
            }
        }

        stage('Run Regression Tests') {
            steps {
                bat '"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\Extensions\\TestPlatform\\vstest.console.exe" "C:\\Users\\PrathameshBabanHarad\\source\\repos\\Training_UIAutomationFramework\\Tests\\bin\\Release\\Tests.dll" /Logger:trx'
            }
        }

        stage('Publish Test Results') {
            steps {
                junit '**/TestResults/*.trx'
            }
        }
    }

    post {
        always {
            // Publish test results
            junit '**/*.trx'
        }
    }
}